#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings

title: Einführung in Data Science
author: Steffen Herbold
copyright: "2021"
logo: logo.png

repository:
  url: https://github.com/sherbold/TODO
  
  
html:
  use_repository_button: true
  
only_build_toc_files: true

execute:
  execute_notebooks: off